# Format of RAMM deployment configuration files:
# * exactly *one* of every field except `[[assets]]`
#     - the target environment must be one of `active | testnet | mainnet`
#     - the field `ramm_pkg_addr_or_path` must container *either* of
#         * a path to the RAMM Sui Move library, or
#         * an address to a published version of it
#     - the asset count must be at least `2`, and match the number of occurences of `[[assets]]`
#     - the fee collection address must be a valid `sui_types::SuiAddress`
# * there must be at least 2 occurences of `[[assets]]`
# * regarding each asset: all of the fields
#     - `asset_type: sui_types::TypeTag`,
#     - `aggregator_address: SuiAddress`,
#     - `minimum_trade_amount: u64` and
#     - `decimal_places: u8`
#   must be present


# The target network to which the RAMM will be published.
target_env = "testnet"
#ramm_pkg_addr_or_path = "../ramm-sui"
ramm_pkg_addr_or_path = "0x71842d2b44e795901b99be7ba1d9db524ee5df6674cc0270088db4e95166dd89"
asset_count = 3
fee_collection_address = "0x899b0e93970b774c2f007485f5812671eff5c84549741c76fc900e9aab857965"

[[assets]]
asset_type = "0x937e867b32da5c423e615d03d9f5e898fdf08d8f94d8b0d97805d5c3f06e0a1b::test_coins::ADA"
aggregator_address = "0xde1e536f6938c718bdaa055e75ae50ec3fa6691726b3a3b897c691355793ede6"
minimum_trade_amount = 100_000_000
decimal_places = 8

[[assets]]
asset_type = "0x937e867b32da5c423e615d03d9f5e898fdf08d8f94d8b0d97805d5c3f06e0a1b::test_coins::DOT"
aggregator_address = "0xa6c61dae96bcae8944ca1365f943b44a2def64a3e1ae291eef76879868e157c7"
minimum_trade_amount = 10_000_000
decimal_places = 8

[[assets]]
asset_type = "0x937e867b32da5c423e615d03d9f5e898fdf08d8f94d8b0d97805d5c3f06e0a1b::test_coins::SOL"
aggregator_address = "0x35c7c241fa2d9c12cd2e3bcfa7d77192a58fd94e9d6f482465d5e3c8d91b4b43"
minimum_trade_amount = 1_000_000
decimal_places = 8