[package]
name = "ramm_sui"
version = "0.0.1"
edition = "2024.beta"
# First version of package published in testnet with ID:
#published-at = "0xd3283fa556731370cd2a7f389b3e35c630184118b5af416ce9e57edfce751496"
# Upgraded to ID:
#published-at = "0xb93c139768a9dfdb6898475052be3ac1d93b92dccf2288c96a8e227f3e511ef6"

# First version of package published in mainnet with ID:
#published-at = "0xd4e097d82d73dc5d152f277bd17ba7980cad4c0b238c3609517cbd0cf686ddd1"
# Upgraded to ID:
#published-at = "0xcb6640194b37023f6bed705f40ff22883eb6007d4c69e72c317c64671f9f6b29"
# Upgraded to ID:
# published-at = "0xce6fe657125970687c9065815974a351fe7c0389589308816740bd5197c220a4"
# The above ID was done in the `imbr-ratio-event` branch, as otherwise it would not be possible
# to upgrade the package - a public function's signature was altered since that branch's PR was
# merged to `main`: `ramm_sui::math::{check_imbalance_ratios, imbalance_ratios}`

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "mainnet" }
SwitchboardStdLib = { git = "https://github.com/switchboard-xyz/sbv2-sui.git", subdir = "move/mainnet/switchboard_std/", rev = "main" }

[addresses]
ramm_sui = "0x0"
std = "0x1"
sui =  "0x2"
# mainnet
switchboard = "0x08d79f4d920b03d88faca1e421af023a87fbb1e4a6fd200248e6e9998d09e470"
# testnet
#switchboard = "0x98670585b87e06628ef2d7f7cb1e7bee8ada65b43b82997935225a7e6e21d18e"
