name: CI for `ramm-sui` Sui Move smart contract
run-name: GitHub Actions CI for `ramm-sui`
on: [push, pull_request]

jobs:
    install-sui-binaries:
        name: cargo test
        runs-on: ubuntu-latest
        steps:
        - uses: dtolnay/rust-toolchain@stable
        - run: |
            cargo install --locked --git https://github.com/MystenLabs/sui.git --branch mainnet sui
    ramm-misc-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                cd ./ramm-misc
                sui move build
                sui move test
    ramm-sui-deploy-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                cd ./ramm-sui-deploy
                cargo build
